---
- name: Configure MySQL, Tomcat, Memcached, Redis, and Deploy WAR
  hosts: node
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Install Tomcat
      apt:
        name: tomcat9
        state: present

    - name: Start and enable Tomcat service
      service:
        name: tomcat9
        state: started
        enabled: yes

    - name: Install Memcached
      apt:
        name: memcached
        state: present

    - name: Start and enable Memcached service
      service:
        name: memcached
        state: started
        enabled: yes

    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: sample.war
        dest: /var/lib/tomcat9/webapps/
      notify:
        - Restart Tomcat
          
  handlers:
    - name: Restart Tomcat
      service:
        name: tomcat9
        state: restarted

  